[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = []

[start]
cmd = "node index.js"

[variables]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
